### ISSUE TITLE
Look into brightbox for easier nginx and passenger deployment.

### ISSUE THREAD

**Issue by Bialogs** [mitre-cyber-academy/ctf-scoreboard#10]
Migrated from Trello

**Comment by Bialogs** [comment]
https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng

Seems that Brightbox is not maintaining Nginx / Passenger versions anymore.

**Comment by rbclark** [comment]
Well that pretty much closes out this then, [we pull our ruby version from bightbox](https://github.com/mitre-cyber-academy/rails-app-cookbook/blob/master/recipes/default.rb#L53) but let a different cookbook take care of installing passenger and nginx at this point anyway.
