### ISSUE TITLE
Provide README / install steps / documentation

### ISSUE THREAD

**Issue by noraj** [mitre-cyber-academy/ctf-scoreboard#117]
- [ ] README: general description of the app, links for Install steps &  documentation, licence, etc...
- [ ]  installation steps: provide `INSTALLATION.md` or provide some installation steps in the documentation
- [ ] documentation: provide a documentation with installation steps, some non intuitive stuff about managing the app, dev tips, etc ...

You can find an Installation guide I made on the wiki : https://github.com/mitre-cyber-academy/registration-app/wiki/Installation

**Comment by noraj1337** [comment]
https://github.com/mitre-cyber-academy/registration-app/pull/121

**Comment by rbclark** [comment]
To add to this it would be wonderful to have screenshots of the scoreboard in action on the README.

**Comment by noraj1337** [comment]
https://github.com/mitre-cyber-academy/ctf-scoreboard/wiki/Screenshots

**Comment by noraj1337** [comment]
You will need to help me with production steps and configuration on the wiki.

https://github.com/mitre-cyber-academy/ctf-scoreboard/wiki/Installation
https://github.com/mitre-cyber-academy/ctf-scoreboard/wiki/Configuration

**Comment by rbclark** [comment]
I like the screenshots! As for the production steps, we normally just run on Heroku, and the app is setup in a manner where if you just push it to Heroku, link a Postgres database, link Sendgrid, and set the `S3_BUCKET`, `S3_KEY`, and `S3_SECRET` if you are using the VPN certificate sync functionality then everything will just work for you. We used to run on Dokku and the configuration was very similar. After using Heroku and Dokku I strongly suggest deploying the app using one of the two.

**Comment by rbclark** [comment]
Closing issue since I believe @noraj has addressed most of these issues.

**Comment by noraj** [comment]
@rbclark I agree except one point maybe. It would be so much better if you could describe parameters  in config files or at least improve the [Configuration](https://github.com/mitre-cyber-academy/ctf-scoreboard/wiki/Configuration) wiki page.
Because some stuff like in https://github.com/mitre-cyber-academy/ctf-scoreboard/blob/master/config/environments/production.rb are designed to work with Heroku, etc...

**Comment by rbclark** [comment]
I have added some links to useful documentation for each variable, I hope thats helpful.

**Comment by noraj** [comment]
@rbclark Thx
