### ISSUE TITLE
Add recaptcha to sign up page and challenge submission

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/ctf-scoreboard#134]
We need to have a recaptcha on the registration page (and maybe challenge submission as well). Looks like theres a lot of gems that will make this pretty easy.

**Comment by noraj** [comment]
Is Recaptcha optionnal during deployment ?

**Comment by rbclark** [comment]
Yep, you can just set `RECAPTCHA_DISABLE=true bundle exec rails s`
