### ISSUE TITLE
Add countries to registration

### ISSUE THREAD

**Issue by Gitoffomalawn** [mitre-cyber-academy/ctf-scoreboard#153]
During registration it is assumed the user is US-bound, and no other registration countries are offered. Please add the option to register under other countries as well.

**Comment by rbclark** [comment]
The state dropdown does offer a "Outside US" option as an option. With that said we could update the mouse over text to include an instruction to choose "Outside US" if you are not US based in case users do not see it.

**Comment by noraj** [comment]
This is may be a little too targeting MITRE CTF. May be it will be better and make the framework for more general use if you do this:

+ let select people their contry (full country list)
+ make configurable for admin if a country (ex: USA) should be the default country to get something like USA or non-USA.

For example, I'm not in USA and if I decide to host a CTF this behavior will need dev to be modified.

**Comment by Gitoffomalawn** [comment]
What @noraj says is more to my point. Using the framework as is, is likely to raise eyebrows in settings that are outside the US. It would be more logical to have a dropdown to select a country (mandatory entry), and have a state/province optional field. To summarize:
- Consider adding country selection field (mandatory)
- Also add a state/province field (non-mandatory), with maybe a toggle for the admin to mark it as mandatory if desired

**Comment by Gitoffomalawn** [comment]
And sorry for that. Wrong button.

**Comment by rbclark** [comment]
I agree for the purpose of competitions outside the US that this may seem a bit strange. A full customization list here would be a bit difficult and seems unnecessary to implement. I would be okay with a country dropdown that then dynamically asks state or other information once it is selected, however I don't see us ever implementing this. With that said I'm willing to consider pull requests for such a feature.

**Comment by Bialogs** [comment]
@rbclark Do we want to revisit this a little more with all the params work we are doing?
