### ISSUE TITLE
Registration email format

### ISSUE THREAD

**Issue by Gitoffomalawn** [mitre-cyber-academy/ctf-scoreboard#154]
The registration page accepts non-email format strings as input (i.e. "test", "not-an-email.fake", as opposed to "test@example.com"), and completes registration regardless of what is filled in.  #Logging in, however, will fail, since the login field expects, and validates the input of, an email format string.

As a result, accounts can be registered that cannot be used to log in.

**Comment by rbclark** [comment]
Good call, fix incoming.
