### ISSUE TITLE
How can I login into the administrator account ?

### ISSUE THREAD

**Issue by noraj** [mitre-cyber-academy/ctf-scoreboard#158]
`http://localhost:3000/admin` redirects to `http://localhost:3000/`.

![](https://i.imgur.com/qoCCBiW.png)

On `http://127.0.0.1:3000/users/login`, login as `root@root.com` or `ctf@mitre.org` results into an error message `You have to confirm your account before continuing.`.

![](https://i.imgur.com/TaWxe9e.png)

How can I login into the administrator account ?

**Comment by rbclark** [comment]
You are supposed to be able to login through the users login page, there is not a separate login for admins. Try doing the following:

```
user = User.where(email: 'root@root.com')
user.confirm!
user.save
```

and then try to login again.

**Comment by noraj** [comment]
@rbclark I'm totally RoR ignorant, where you I paste this ruby code ?

**Comment by rbclark** [comment]
Sorry, you have to paste that in using rails console: `bundle exec rails c`

**Comment by rbclark** [comment]
My mistake, it is `user.confirm` not `user.confirm!`. The rest of the steps should be correct.

**Comment by noraj** [comment]
@rbclark Of course I tested `user.confirm` too but it doesn't exist either.
I also checked all available methods but none are similar to confirmation.

![](https://i.imgur.com/fRs7wDy.png)

**Comment by rbclark** [comment]
I didn't read your error message well enough, my bad. You need to only have 1 user that you are operating on, however you are operating on an activerecord relation (aka an array of users, in your case an array of 1 users), which is my bad since you were just following my instructions. The following will work:

```
user = User.find_by(email: 'root@root.com')
user.confirm
user.save
```

**Comment by noraj** [comment]
Sorry, I'm familiar with ruby but not with RoR so I didn't understand that activerecord relation was an array.
Thanks for the explanation, this is working now.

I think those steps are not obvious for non-developers so where can we add them? What is the more suitable place: Wiki or Readme?
You must think that confirming those accounts by defaults is a security issue on some environments, I agree with you.

**Comment by rbclark** [comment]
For the development environment I don't mind confirming by default. That should be doable with a correction to the seeds file.

**Comment by noraj** [comment]
See my PR #161
