### ISSUE TITLE
Add responsible whitecell member to challenge

### ISSUE THREAD

**Issue by Bialogs** [mitre-cyber-academy/ctf-scoreboard#221]
As competitors have questions about challenges they want to know who is responsible for it. It would be nice that when we create challenges we can (optionally?) include an admin's chat username so people know who to message. This would be seen below the description.

**Comment by noraj** [comment]
I'm not saying it is a bad idea, generally people put `Author: xxx` in the description.
Orga just have to put that in their template for challenge creators. I don't think a dedicated field with a corresponding database entry is necessary.
