### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by noraj** [mitre-cyber-academy/ctf-scoreboard#268]
Dockerize the platform:

- create a docker folder
- provide a dockerfile
- provide a docker-compose file (with postgresql config, etc.)
- add wiki entry about docker

**Comment by rbclark** [comment]
Docker may be easier for some people, I do think overall that running with Dokku as we recommend is a bit better though, all it is really doing is running Docker in the backend.

**Comment by noraj** [comment]
I yeah I forget about [Dokku](https://github.com/dokku/dokku) that claims itself:

> Docker powered mini-Heroku.

I don't really know what is dokku and how it works, but if it is a docker with Herroku inside it will be pretty much the same, the README is just lacking steps on how to install the app with Dokku so.

**Comment by noraj** [comment]
@rbclark For the docker part you can easily mimic https://github.com/Abdulwahaab710/CTFDashB

**Comment by noraj** [comment]
I'd like to see how to deploy with dokku if it is the most tested way.

**Comment by rbclark** [comment]
@noraj, I have posted instructions on how to do so on the wiki: https://github.com/mitre-cyber-academy/ctf-scoreboard/wiki/Production-Installation

**Comment by noraj** [comment]
@rbclark I'll check it out.
