### ISSUE TITLE
Users can exist as the team captain without being included in users

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/ctf-scoreboard#33]
We have a strange case where a user managed to register and create a team and somehow remove themselves from the team but remain as the team captain. This breaks the export script so we kinda need to figure out how to fix it at some point. The team was team number 241 and user 621. It may represent a bug in the team destroy or user destroy code.

**Comment by James-Tobin** [comment]
can be reproduced by running the server locally behind a proxy.  When a user tries to make a team the Geocoder throws an error, this stops the user from being added to the users on a team, but makes them team captain still

**Comment by rbclark** [comment]
The fix in this case is probably to not have the team save fail if geocoding fails.
