### ISSUE TITLE
Challenges solved per hour is not correct

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/ctf-scoreboard#338]
There are cases where challenges solved per hour does not display correctly, mainly due to the full date missing from each hour. Need to include more than just 5:00pm and actually include some of the rest of the date for it to work correctly. There are some teams that are showing weird flags per hours graphs due to this.

**Comment by camdenmoors** [comment]
Should be fixed now with PR #471.

**Comment by rbclark** [comment]
Fixed in https://github.com/mitre-cyber-academy/ctf-scoreboard/commit/db8b7d0d72b46b40d8b7a1fa336ef3c27e3b7b56
