### ISSUE TITLE
Disable flags per hour graph does not work

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/ctf-scoreboard#367]
Currently checking the `disable_flags_an_hour_graph` option does not actually change anything. Looking through the code it isn't actually referenced anywhere. Removing the `disable_flags_an_hour_graph` column in the database is an acceptable fix to this issue.

**Comment by camdenmoors** [comment]
![Annotation 2020-06-11 153942](https://user-images.githubusercontent.com/66680985/84431758-d52e2900-abf9-11ea-9aa7-981a1b16896b.png)
I think that this bug has been fixed in [this](https://github.com/mitre-cyber-academy/ctf-scoreboard/commit/771df4f122d4fb866e44c952d44b0282aa29fa10) commit
