### ISSUE TITLE
Make team clickable in Team x Challenges scoreboard layout

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/ctf-scoreboard#408]
Currently the team name is not clickable in the Teams X Challenges scoreboard layout, need to make it clickable.

**Comment by camdenmoors** [comment]
Seems this was done [here](https://github.com/mitre-cyber-academy/ctf-scoreboard/commit/771df4f122d4fb866e44c952d44b0282aa29fa10#diff-1b2afbc07e5cd170ca5ca9ff63135c6b).
