### ISSUE TITLE
Make Teams and Challenges clickable in the Solved Challenges table

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/ctf-scoreboard#409]
Currently challenge name and team name are just text, need to make these clickable.

**Comment by camdenmoors** [comment]
Seems this was fixed [here](https://github.com/mitre-cyber-academy/ctf-scoreboard/commit/771df4f122d4fb866e44c952d44b0282aa29fa10#diff-9c9801f0e303ea5f2c571380d1419e9f).

**Comment by rbclark** [comment]
Yep you are correct!
