### ISSUE TITLE
Design Phase Challenges say "Click to Solve" even when they are closed

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/ctf-scoreboard#410]
If you’re a team, and design phase challenges are no longer open, they still say “click to solve”, even though they’re no clickable. Perhaps a textual change would be useful?

**Comment by Bialogs** [comment]
I think the difference is that I'm checking to see if they are solved, not "closed"

**Comment by rbclark** [comment]
I think this is now fixed in master, I just left it open as something to check once again once I complete #401

**Comment by rbclark** [comment]
This looks to still be fixed even after the refactor, closing.
