### ISSUE TITLE
Investigate challenge sorting order

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/ctf-scoreboard#411]
Currently design phase challenges are apparently sorting by last solve which is variable. It would be better to sort this table by :created_at time if possible.

**Comment by camdenmoors** [comment]
I'm not able to replicate this, is this still happening for you?

![replicate](https://user-images.githubusercontent.com/66680985/85886228-a98f6f00-b7b3-11ea-96b1-786514df8633.gif)

**Comment by rbclark** [comment]
If you are logged in as an admin in that screenshot then that doesn't actually submit a flag, it just tests whether you put the correct text in (to make it easier to test as an admin). However I believe you are correct this issue does not seem to happen anymore.
