### ISSUE TITLE
Run spellcheck on I18n

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/ctf-scoreboard#413]
With the move of most strings in the application in the registration I18n file, it would be great to have a spellcheck rake task on this as part of the CI pipeline.

**Comment by camdenmoors** [comment]
I'm not sure how feasible this is or how needed it is. From what I can tell there aren't any actively maintained gems that can run spell checks on singular files. [I've created a tool](https://github.com/camdenmoors/ctf-scoreboard/blob/spellcheck_i18n/test/spellcheck_i18n.py) (Python) that extracts the strings from the yml files and checks them, however it is far from perfect (suggestion-wise and performance-wise), would require integrating python into the test environment, and would mix languages.

It has found some mistakes that I will fix in a PR:

![badspelling](https://user-images.githubusercontent.com/66680985/85429048-228c8d80-b54c-11ea-9fd0-f24710e641eb.png)

**Comment by rbclark** [comment]
https://github.com/segabor/Hunspell seems reasonable enough since it is just an interface to the spellchecker that OpenOffice and Mozilla use. We would have to bring our own EN dictionary but thats reasonable enough if we just dump it in the tests directory and use Git LFS. In Ruby it should be possible to create a rake task or a test of some sort that loads all files in `config/locales`, splits on each word and runs Hunspell on it.
