### ISSUE TITLE
Cleanup rails-admin views

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/ctf-scoreboard#415]
Currently rails-admin has a lot of information it shouldn't have, making it easy for users to be prompted for unnecessary data. For example, it is possible for users to create challenge_category objects, which should be completely hidden. Also we should hide or remove the add button on a lot of the base models in rails-admin to force users to create the right type of challenge (StandardChallenge, PentestChallenge, or ShareChallenge).

**Comment by camdenmoors** [comment]
Rails admin is cleaned up in #478
