### ISSUE TITLE
Compete for Prizes text is currently broken

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/ctf-scoreboard#529]
The translation seems to be broken.

<img width="327" alt="Screen Shot 2020-07-17 at 10 52 18 AM" src="https://user-images.githubusercontent.com/2308869/87799803-a835ed00-c81b-11ea-883f-81de1a7be1a3.png">

**Comment by camdenmoors** [comment]
This is fixed in #519 [here](https://github.com/mitre-cyber-academy/ctf-scoreboard/pull/519/files#diff-203683e2fda64e0d4c25a8c0c8f48868).
