### ISSUE TITLE
Flag Submission box does not disappear until full page reload

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/ctf-scoreboard#530]
Currently when a user submits a flag the Flag Submission box still displays until page reload.

The desired behavior is as follows:

- Admins can submit the same flag over and over and it should never create a solved challenge, and therefore they will only be shown the text saying "Flag Accepted" but after page reload they will be able to submit again.
- Players should only be able to submit a flag once, and once they see "Flag Accepted" they should not have the option to resubmit.

![Screen Recording 2020-07-17 at 10 58 57 AM](https://user-images.githubusercontent.com/2308869/87801117-3eb6de00-c81d-11ea-95e2-d0991cf7a94b.gif)

Tests to verify this behavior would be awesome, since admins are unable to verify it by hand without creating a team account.

**Comment by camdenmoors** [comment]
Should be fixed with Sean's #532

**Comment by sesheikholeslam** [comment]
> Should be fixed with Sean's #532

Unfortunately I think the fix I made in that PR makes the flag submission box disappear when the user submits both a correct and incorrect flag.
