### ISSUE TITLE
Force_close does not work 

### ISSUE THREAD

**Issue by Bialogs** [mitre-cyber-academy/ctf-scoreboard#7]
When a game is closed & logged in as admin, both force_closed and closed do not show a challenge as red

**Comment by rbclark** [comment]
Its not quite that it doesn't work, the issue is involving the code handling the color which should be set to a challenge, locking a challenge that already has solved challenges or submitted keys seems to be the root of the issue.

**Comment by Bialogs** [comment]
closed by 154f326
