### ISSUE TITLE
Creating scope :open. Overwriting existing method Challenge.open.

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/ctf-scoreboard#77]
This is only showing up on production when you run rails c, not sure what is causing it.

**Comment by aarongray** [comment]
I believe its happening because Ruby's kernel has an `open` method on it.

See:
https://ruby-doc.org/core-2.5.0/Kernel.html#method-i-open
https://github.com/rails/rails/issues/31234

One solution would be to rename your scope from `open` to something else.

**Comment by rbclark** [comment]
Not sure when this error was resolved but this is no longer happening on `rails c` or `rails s`, closing.
