### ISSUE TITLE
Rename Repository

### ISSUE THREAD

**Issue by Bialogs** [mitre-cyber-academy/ctf-scoreboard#90]
No longer a registration site

**Comment by noraj1337** [comment]
Yes and state that https://github.com/mitre-cyber-academy/ctf-scoreboard is deprecated.

**Comment by noraj1337** [comment]
https://github.com/mitre-cyber-academy/registration-app --> https://github.com/mitre-cyber-academy/ctf-scoreboard

Thanks GitHub provides redirection. [Link updated](https://gitlab.com/noraj/rawsec-cybersecurity-list/commit/610aa8abf69e109f247de150670c28c76dab14cc) anyway. You may want to know that you are referenced under [Rawsec's CyberSecurity Inventory](http://list.rawsec.ml/index.html) on the [CTF platforms page](http://list.rawsec.ml/ctf_platforms.html). I take advantage of the opportunity to say that MITRE CTF Scoreboard is one of the rare true alternative to CTFd (python) or Mellivora (PHP). MITRE CTF Scoreboard seems well featured, maintained (that's rare), and well designed (that's also rare). The only black spot for now is the lack of documentation.

As I said I would be proud to help.

**Comment by Bialogs** [comment]
Thanks for the kind words!
